### ISSUE TITLE
'undefined' is not a function (evaluating 'removeCloak.bind(this, iElement)')

### ISSUE THREAD

**Issue by rcollette** [angular-translate/angular-translate#1727]
### Subject of the issue
undefined function when upgrading from 2.12.0 to 2.15.1

### Your environment
* Version 2.15.1
* AngularJS 1.
* Mozilla/5.0 (x11; Linux i686) Apple/Webkit/534.34 (KHTML, like Gecko) 
This is a QT 4.8.4 webview control running on an device

### Steps to reproduce
Not totally sure but appears to have something to do with using data-translate-cloak directive.

### Expected behaviour
Cloaking behavior (compile/linking) should work.

### Actual behaviour
Getting the error `'undefined' is not a function (evaluating 'removeCloak.bind(this, iElement)')`

angular-translate.js line 3422

Appears to related to this commit
https://github.com/angular-translate/angular-translate/pull/1689/files

I've looked at the source and I can't tell why or how the removeCloak function could possibly be undefined at the call site.

![img_20170502_155406](https://cloud.githubusercontent.com/assets/136476/25665478/b5f0c5d0-2feb-11e7-9225-4e71a2243f92.jpg)

**Comment by knalli** [comment]
Hello,

as we had already mentioned in the [issue's template](https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md), we need a working and as minimal as possible demo covering your specific use case or issue. 

Follow these steps:
1. Please open [this plnkr base](https://plnkr.co/edit/8vRLnfGmtg51qZFfDeVc?p=preview).
2. Fork it (at the top left).
3. Ensure the version of AngularJS and angular-translate is correct.
4. Ensure all angular-translate plugins are available; reduce and remove anything you can.
5. Write a minimal as possible demo for your specific issue.
6. Save and freeze. Provide us the final link to your demo.

**Comment by knalli** [comment]
Hello,

this is a general reminder: We are still waiting for your reply with additional details. If you cannot help us, we cannot help you.

Looking forward to hear from you.
